# 生产环境配置（使用 Nacos 配置中心）
spring:
  config:
    import:
      - optional:nacos:valhalla-auth.yaml?refreshEnabled=true
  cloud:
    nacos:
      config:
        server-addr: localhost:18848
        namespace: prod
        group: DEFAULT_GROUP

logging:
  level:
    root: warn
    com.yggdrasil.labs.*: warn
